AllCops:
  Exclude:
    - 'lib/light-service.rb'
    - 'vendor/bundle/**/*'
    - 'gemfiles/vendor/bundle/**/*'
    - 'bin/*'
    - 'light-service.gemspec'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/PredicateName:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Metrics/MethodLength:
  Max: 15
