language: ruby

rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - 2.3.0

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler
  - bundle install --path vendor/bundle

# uncomment this line if your project needs to run something other than `rake`:
script:
  - bundle exec rspec spec
  - bundle exec rubocop

gemfile:
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfileset
